### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by afritz1** [afritz1/OpenTESArena#44]
I've linked my project with Travis CI, and all I need now is the `.travis.yml` file, but the examples I've seen so far have more scripts and extra things in them than I currently need, and it's a bit confusing.

Could someone give an example below? I'm looking for something along the lines of:

```yaml
language: cpp
os: linux
compiler: gcc
before_install:
- sudo apt-get install libsdl2-dev
- sudo apt-get install libsdl2-image-dev
- sudo apt-get install libopenal-dev
- sudo apt-get install libopencl-dev
- sudo apt-get install wildmidi
```

or

```yaml
language: cpp
os: linux
compiler: gcc
script: cmake ...
```

I'm not sure what all is needed, though.
